### ISSUE TITLE
Add support for a json file as the request body

### ISSUE THREAD

**Issue by daleal** [daleal/zum#8]
It would be nice to be able to just specify a file name and then have `zum` open that file and use its contents as a request body.

**Comment by sehnsucht13** [comment]
Hello!

I have started working on this issue and I have currently implemented all the logic necessary to use a file as the body of a request. The only thing I am wondering about is what should the variable containing the path to the request body be called in the `zum.toml` file?

Currently, I have it working with this:
```toml
[endpoints.test-post]
route = "/test-post"
method = "post"
bodyPath = "/some/path/to/request_body_file"
```
The `bodyPath` variable is used to store the (relative or absolute) path to the file. Should the variable be called something else? Maybe, we can check if the `body` variable contains an array/list or a string. If it contains a list then it is treated as normal and if it contains a string then that string is treated as a file path to the body file. What do you think?

I have made a pull request containing my work so far if you would like to take a look at it. 

P.S: Sorry for not claiming this issue earlier. I forgot to make a comment on the Issue tracker before starting.

**Comment by daleal** [comment]
Hi @sehnsucht13! First of all, **thank you** for contributing to Zum!

To be consistent with the rest of the API, I think that it might be a good idea to declare that **a file will be used** from the config file and then pass the file path from the `zum` CLI. I think that the instruction for the body to be received as a `json` file should be given on the same `body` attribute, so Zum could check if the `body` parameter is a string or an array to determine what it needs to receive from the CLI. For example:

```toml
[endpoints.example]
route = "/endpoint"
body = "json"
```

That way, you could call:

```sh
zum example ./requests/body.json
```

This way, we avoid letting the user define an ignored `body` parameter. It also leaves open the possibility to, in the future, implement other formats for that file, for example:

```toml
[endpoints.example]
route = "/endpoint"
body = "toml"
```

That way, you could call:

```sh
zum example ./requests/body.toml
```

What do you think?
